### ISSUE TITLE
OrderSet validation failed (sprint2-test)

### ISSUE THREAD

**Issue by HMoneda** [Nostradongus/AGC-Print#11]
### Summary:
Confirmed Orders are not being stored in the database after ordering

### Steps to Reproduce:
1. Go to new order
2. Create an Order
3. Confirm order in cart
4. Enter delivery info
5. place order

### Expected Result
OrderSet stored in the database

### Actual Result
OrderSet is not stored in the database

### Error Message
![image](https://user-images.githubusercontent.com/80668451/129888843-04aa8ec7-78cd-4459-a64e-29404f7d4c70.png)

**Comment by Nostradongus** [comment]
Bug fixed / resolved! Thank you very much.
