### ISSUE TITLE
Extra space in getAllPastOrderSets function

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#12]
**SUMMARY:**

<img width="610" alt="08-19-order_service" src="https://user-images.githubusercontent.com/80932912/130078194-19229ad1-28b5-4382-b26e-9dfa20cedc40.PNG">

In order_service.js, there is an extra space in the getAllPastOrderSets function { status: 'Complete' }.

**On Branch: sprint2-test**

**Comment by Galahallt** [comment]
I overlooked the space my bad. This issue is resolved. Thanks!
