### ISSUE TITLE
getUserPayments function does not send message for no payment receipts uploaded

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#13]
**SUMMARY:**

In payment_controller.js, the getUserPayments function does not successfully check for payment receipts uploaded from user. As it still returns status 200 even if no payment has been uploaded yet.

Where the issue is found / Suggested fix (Check if payments.length != 0): 

<img width="552" alt="08-19-getUserPayment-check" src="https://user-images.githubusercontent.com/80932912/130091783-c333f6af-74db-4942-98da-b9603aacb05b.PNG">

On Branch: sprint2-test

Thank you.

**Comment by Nostradongus** [comment]
resolved! thank you very much!
