### ISSUE TITLE
Filename and filepath are null in database when submitting a report

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#14]
**Summary:**
filename and filePath are null when uploading a report in database.

**Steps to recreate:**
- Submit a report for an order
- Check the report in the database (filename and filePath are null)

**Suggested fix:**
<img width="420" alt="08-22-null-filename-report" src="https://user-images.githubusercontent.com/80932912/130345100-3ae41cb2-62ff-4ada-94ed-238abdcabd06.PNG">

**On branch:** sprint2-test

**Comment by Nostradongus** [comment]
Resolved, thank you very much!
