### ISSUE TITLE
Error in sorting of past orders 

### ISSUE THREAD

**Issue by JulCL123** [Nostradongus/AGC-Print#27]
Summary : In order history, some orders are not sorted from most recent to least recent. This happens when two order sets are made within 5 mins or less. 

Branch : sprint2-test

Steps : 
- order a tarpulin 
- confirm your order and add delivery address manila
- order a wallpaper
- confirm your order and add delivery address pasig
- in order history manila will be shown first then pasig after even when the order for pasig is the most recent one

**Comment by Nostradongus** [comment]
hello Julian! can you please show me a screenshot of the two order sets' data in the mongodb atlas database? (assuming you are using the mongodb atlas database server one)

**Comment by JulCL123** [comment]
Hello! I used the local db instead of atlas. 
![Capture](https://user-images.githubusercontent.com/77001355/131243730-d0636646-b585-478d-bbed-f00ba0bf5303.JPG)

**Comment by Nostradongus** [comment]
Thank you for the screenshots! Bug resolved! 

To test if it is fixed, create new order sets as I have modified some attributes in the models of Order Set and Order.
