### ISSUE TITLE
Cannot view information page of a user with no existing orders 

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#34]
**Summary:**
Cannot visit the information page of a user with no existing orders in the database. (Gets stuck at "Loading data, please wait...")

**Steps to recreate:**
1. Go to http://localhost:3000/view-user-list
2. View user information of a user with no existing orders in the database
3. Check command line for 404 error

**On branch:**
sprint3-test

Thank you

**Comment by Nostradongus** [comment]
Resolved! Thank you!
