### ISSUE TITLE
Blank inputs are accepted when editing order set and orders

### ISSUE THREAD

**Issue by JulCL123** [Nostradongus/AGC-Print#38]
Story : US#10 

Summary : When editing the order set, text fields accept even when they are blank (e.g. name of the receiver, email address). This also applies when editing orders (e.g. dimensions of the orders (width and height). The blank text field does not however reflect on the database. I think it would be better to not accept blank text fields to avoid confusion.

**Comment by Galahallt** [comment]
This is fine because when inputs are blank, the data stored in the database will not be replaced.
