### ISSUE TITLE
Frame finishing and stretcher frame edges can be left blank

### ISSUE THREAD

**Issue by JulCL123** [Nostradongus/AGC-Print#40]
Story : US10

Summary : When editing a canvas print order, both frame finishing and stretcher frame edges can be left as "select one" depending on the order.  

Steps : 
- click edit order of a canvas print order
- change the frame to either glassless frame or shadow box if the order is either in 3/4 or 1.5 and vice versa
- leave frame finishing or stretcher frame edges as "select one"
- click the update information

**Comment by Galahallt** [comment]
Resolved. Please check.

**Comment by JulCL123** [comment]
An error will show when first changing the frame that the user must choose. It does not show the error again if it was changed back before clicking update information. 

Steps :

- click edit order of a canvas print order
- change the frame to either glassless frame or shadow box if the order is either in 3/4 or 1.5 and vice versa
- choose white edges if 3/4 or 1.5 or choose black if glassless frame or shadow box
- change the frame back to its original (if 3/4 or 1.5 then change it to glassless frame or shadow box then if glassless frame or shadow box to 3/4 or 1.5)
- leave the dropdown to select one
- click the update information

**Comment by Galahallt** [comment]
Noted. Fixed the issue above. Verify if it is already fixed.
