### ISSUE TITLE
Issue with editing order sets of users with nine digit contact number 

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#41]
**Summary:**
If the user inputted a nine digit contact number in the delivery information page, their order set would not be editable by the admin without changing the contact number first.

**Steps to recreate:**

1. As a client, place an order
2. In the delivery information page input a 9 digit contact number
3. Next, as an admin user check visit the order-details page of this order
4. Click the Edit Order Set button
5. Click the update information button
6. Field will display "The maximum length allowed is 10"

**On branch:**
sprint3-test

Thank you

**Comment by Galahallt** [comment]
Resolved. Please check again.
