### ISSUE TITLE
Cannot upload payment receipt as a client 

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#44]
**Summary:**
As a client, the upload receipt button in the payment portal does not go through

**Steps to recreate:**
1. As a client, go to an order where in they can pay
2. Try to upload a payment receipt
3. Check command line for error (UnhandledPromiseRejectionWarning: ValidationError: Payment validation failed: userFullName: Path `userFullName` is required.)

**On branch:**
sprint3-test

Thank you

**Comment by Nostradongus** [comment]
Resolved! Please wait for the changes to be pushed na lng!
