### ISSUE TITLE
contact number and order status of edit order set form 

### ISSUE THREAD

**Issue by JulCL123** [Nostradongus/AGC-Print#46]
Summary : The numbers +63 are overlapping with the contact number text field. The order status overlaps with update information. 

Branch : sprint3-test

Steps : 
- open any order set
- click edit order set

This is what it currently looks like on my end 

![error1](https://user-images.githubusercontent.com/77001355/133193491-55899027-dac8-40e5-bf10-3c56053ce40f.JPG)

**Comment by Galahallt** [comment]
Might be because of the zoom size. I modified the modals. Check if it is better.
