### ISSUE TITLE
Payment receipt in PDF format cannot be downloaded

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#47]
**Summary:**
Both as a client and a admin, PDF payment receipts cannot be downloaded

**Steps to recreate:**
1. As a client, upload a payment receipt in PDF format
2. Try to download it (cannot download)
3. Also try to view as an admin, view this payment and try to download it (check 401 error in chrome dev tools)

**On branch:**
sprint3-test

Thank you

**Comment by Nostradongus** [comment]
Good evening! For this pala, apparently kailangan premium account ung Cloudinary para maka access and download ng uploaded PDFs. With that said, i think this problem will be resolved if we pay for a premium account- which will be done by our client when its time for project signoff.

**Comment by jason-9601** [comment]
Noted @Nostradongus thanks :)
