### ISSUE TITLE
Cannot download preview image in View Payments page

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#49]
**Summary:**
As an admin in the View Payments page (http://localhost:3000/view-payment-list). Viewing it and downloading it does not work successfully (downloads an undefined file).

**Steps to recreate:**
1. As a staff,  go to http://localhost:3000/view-payment-list
2. Pick any payment, click view receipt and download receipt
3. Result is an undefined download

**On branch:**
sprint3-test

Thank you

**Comment by Nostradongus** [comment]
Resolved! Thank you!
