### ISSUE TITLE
Error in editing staff information (contact number and email)

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#51]
**Summary:**
As the system admin, editing staff information is resulting in an error. Specifically with the contact number and email fields.

**Steps to recreate:**
1. As a staff admin, edit information for one staff account. Fill up all fields.
2. Press update information and check command line for error. (ReferenceError: result is not defined)

**On branch:**
sprint3-test

Thank you

**Comment by espiritu-p** [comment]
Seems there was an error for the controller, but I pushed the updates now. Kindly check again if the error still exists.
