### ISSUE TITLE
No token being generated for a newly registered user 

### ISSUE THREAD

**Issue by jason-9601** [Nostradongus/AGC-Print#8]
**SUMMARY:**

After registering a new user and being automatically redirected to http://localhost:3000/my-orders, a token is not generated (underfined) and user is empty. Because of this, a newly registered user would have to logout and login if they want to order.

**STEPS TO RECREATE:**
1. Register a new user
2. Check local storage token and user

**On Branch:** sprint1-test

**Comment by Nostradongus** [comment]
Problem resolved! 

Changes now pushed to the sprint1-test branch

Thank you very much!

**Comment by Nostradongus** [comment]
Paki close na lng ng branch, thank you!

**Comment by Nostradongus** [comment]
Problem resolved! 

Changes now pushed to the sprint1-test branch

Thank you very much!
